export const filterData = [
  {name: 'Indoor', image: require('../../aseets/khana1.png'), id: '1'},
  {name: 'Food', image: require('../../aseets/khana2.png'), id: '2'},
  {name: 'Hotdog', image: require('../../aseets/khana3.png'), id: '3'},
  {name: 'Chinese', image: require('../../aseets/khana4.png'), id: '4'},
  {name: 'Mexican', image: require('../../aseets/khana5.png'), id: '5'},
  {name: 'Sea-food', image: require('../../aseets/p2.jpg'), id: '6'},
];
export const Photos = [
  {type: 'Outdoor', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Outdoor', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
  {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
];
export const highlightData = [
  {name: 'locally Operated', image: require('../../aseets/locallyowed.png')},
  {name: 'Vegeterian', image: require('../../aseets/vegetarian.png')},
  {name: 'Wifi', image: require('../../aseets/wifi.png')},
];

export const restaurantsData = [
  {
    restaurantName: 'Burgers',
    farAway: '21.2',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../../aseets/fd4.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {latitude: -26.1888612, longitude: 28.246325},
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Burgers, Wraps,Milkshakes...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: require('../../aseets/Rstuarents/ch1.webp'),
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: require('../../aseets/Rstuarents/ch2.webp'),
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/Rstuarents/ch3.webp'),
      },
    ],
    photos: [
      {type: 'Outdoor', total: 70, image: require('../../aseets/khana1.png')},
      {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Outdoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
    ],
    id: 0,
  },

  {
    restaurantName: 'Burgers',
    farAway: '21.2',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../../aseets/Rstuarents/fd2.jpg'),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: {latitude: -26.1888, longitude: 28.246665},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Burgers, Wraps,Milkshakes...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: require('../../aseets/Rstuarents/ch1.webp'),
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: require('../../aseets/Rstuarents/ch2.webp'),
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/Rstuarents/ch3.webp'),
      },
    ],
    photos: [
      {type: 'Outdoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Indoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Outdoor', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/fd4.jpg')},
      {type: 'Food', total: 70, image: require('../../aseets/khana4.png')},
    ],
    id: 1,
  },

  {
    restaurantName: 'Steers',
    farAway: '5',
    businessAddress: ' 17 Olivia Rd, Johannesburg',
    images: require('../../aseets/Rstuarents/chinese.png'),
    coordinates: {latitude: -26.1996781, longitude: 28.255879},
    averageReview: 4.9,
    numberOfReview: 1272,
    discount: 12,
    deliveryTime: 25,
    collectTime: 15,
    foodType: 'F-alie grilled beef Burgers',
    productOata: [
      {
        name: 'leand cut chips',
        price: 29.3,
        image: require('../../aseets/khana1.png'),
      },
      {name: 'Big nu', price: 50.8, image: require('../../aseets/khana2.png')},
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/khana3.png'),
      },
    ],
    id: 2,
  },

  {
    restaurantName: 'Rasan Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kenpton Park',
    images: require('../../aseets/Rstuarents/fastfood.png'),
    averageReview: 4.3,
    numberOfRevlew: 706,
    coordinates: {latitude: -26.1845336, longitude: 28.2481691},
    discount: null,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Thicken pizza, Vegetarian pizza. . .',
    productData: [
      {
        name: 'nand cut chips',
        price: 29.3,
        image: require('../../aseets/khana2.png'),
      },
      {name: 'Rig Mac', price: 50.8, image: require('../../aseets/khana3.png')},
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/khana4.png'),
      },
    ],
    id: 3,
  },

  {
    restaurantName: 'RFC',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../../aseets/Rstuarents/mexican.png'),
    averageReview: 4.3,
    numberOfReview: 306,
    coordinates: {latitude: -26.183434, longitude: 28.2434234},
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken,Chicken wings... ',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: require('../../aseets/p2.jpg'),
      },
      {name: 'Big Mac', price: 50.8, image: require('../../aseets/p3.jpg')},
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/khana1.png'),
      },
    ],
    id: 4,
  },
  {
    restaurantName: 'Hotdog',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../../aseets/khana3.png'),
    averageReview: 4.3,
    numberOfReview: 306,
    coordinates: {latitude: -26.1891, longitude: 28.2808},
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken,Chicken wings... ',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: require('../../aseets/p2.jpg'),
      },
      {name: 'Big Mac', price: 50.8, image: require('../../aseets/p3.jpg')},
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/khana1.png'),
      },
    ],
    id: 5,
  },

  {
    restaurantName: 'Salads',
    farAway: '12',
    businessAddress: '22 Bessie street, Cape Town',
    images: require('../../aseets/khana2.png'),
    averageReview: 4.3,
    numberOfReview: 306,
    coordinates: {latitude: -26.4491648, longitude: 28.5541808},
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken,Chicken wings... ',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: require('../../aseets/p2.jpg'),
      },
      {name: 'Big Mac', price: 50.8, image: require('../../aseets/p3.jpg')},
      {
        name: 'Chicken Burger',
        price: 70,
        image: require('../../aseets/khana1.png'),
      },
    ],
    id: 6,
  },
];

export const menuData = [
  {title: 'BEEF', special: false, key: 0},
  {title: 'CHICKEN', special: false, key: 1},
  {title: 'VEGGIE BURGER', special: false, key: 2},
  {title: 'FRIES& CORN', special: false, key: 3},
  {title: 'SALADS', special: false, key: 4},
  {title: 'HAPPY MEALS', special: false, key: 5},
  {title: 'SAHRE BOX', special: false, key: 6},
  {title: 'MILKSHAKES', special: false, key: 7},
  {title: 'COLD DRINKS', special: false, key: 8},
  {title: 'DESSERTS', special: false, key: 9},
  {title: 'HOT DRINKS', special: false, key: 10},
];

export const specialData = [
  {title: 'LIMITED OFFER', key: 0},
  {title: 'GO CHILLI', key: 1},
  {title: 'GO CHEESE', key: 2},
  {title: 'MCCHICKEN DELUXE PROMO', key: 3},
];

export const menu = [
  {key: 1, title: 'BEEF'},
  {key: 2, title: 'CHICKEN'},
  {key: 3, title: 'VEGGIE BURGER'},
  {key: 4, title: 'SHARE BOX'},
  {key: 5, title: 'Happy Meals'},
  {key: 6, title: 'Fries'},
  {key: 7, title: 'Sides'},
  {key: 8, title: 'Milkshakes'},
];

export const menuDetailedData = [
  {
    restaurantName: 'firstrestrant',
    meal: 'Big Mac',
    price: 70.2,
    image: require('../../aseets/p2.jpg'),
    details: 'McFeast features two 100% fresh beef burger patties that are hot',
    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],
    preferenceData: [
      [
        {name: 'Jalapeno Dip1', price: 8.91, checked: false, id: 10},
        {name: 'Sweet & Sour Dip1', price: 8.75, checked: false, id: 11},
        {name: 'BBQ Dip1', price: 11.99, checked: false, id: 12},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 13},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 14},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 15},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 16},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 17},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 18},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 19},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 20},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 21},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 22},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 23},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 24},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 25},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 26},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 27},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 28},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 29},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 30},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 31},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 32},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 33},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 34},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 35},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 36},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 37},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 38},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 39},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 40},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 41},
      ],
    ],
    minimum_quatity: [2, 1, 1, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [true, true, true, false, false],
    id: 0,
    type: 'beaf',
  },

  {
    restaurantName: 'Secondrestrant',
    meal: 'Hand cut chips',
    price: 29.3,
    image: require('../../aseets/khana1.png'),
    details: 'Two 100% fresh beef burger patties that are hot,deliciously',
    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],
    preferenceData: [
      [
        {name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0},
        {name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1},
        {name: 'BBQ Dip', price: 11.99, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke2', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero2', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 0},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 1},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],
    ],
    minimum_quatity: [2, 1, 2, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [false, false, false, false, false],
    id: 1,
    type: 'chicken',
  },

  {
    restaurantName: 'thirdrestrant',
    meal: 'Chicken Burger',
    price: 45.7,
    image: require('../../aseets/khana2.png'),
    details: '',
    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],
    preferenceData: [
      [
        {name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0},
        {name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1},
        {name: 'BBQ Dip', price: 11.99, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 0},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 1},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],
    ],

    minimum_quatity: [2, 1, 1, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [true, true, true, false, false],
    id: 2,
    type: 'notbeaf',
  },

  {
    restaurantName: 'forthrestrant',
    meal: 'Big Mac2',
    price: 50.8,
    image: require('../../aseets/khana4.png'),
    details: 'McFeast features two 100% fresh beef burger patties that are hot',
    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],
    preferenceData: [
      [
        {name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0},
        {name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1},
        {name: 'BBQ Dip', price: 11.99, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 0},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 1},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],
    ],

    minimum_quatity: [2, 1, 1, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [true, true, true, false, false],
    id: '3',
    type: 'veggie',
  },

  {
    restaurantName: 'fifthrestrant',
    meal: 'Hand cut chips',
    price: 29.3,
    image: require('../../aseets/khana3.png'),
    details: 'Two 100% fresh beef burger patties that are hot,deliciously',

    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],

    preferenceData: [
      [
        {name: 'Jalapeno Dip', price: 8.91, checked: false, id: 0},
        {name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 1},
        {name: 'BBQ Dip', price: 11.99, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 0},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 1},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 2},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 0},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 1},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 2},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 3},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 4},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 5},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 6},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 7},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 8},
      ],
    ],

    minimum_quatity: [2, 1, 1, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [true, true, true, false, false],
    id: 4,
    type: 'todo',
  },

  {
    restaurantName: 'sixrestrant',
    meal: 'Big Mac',
    price: 70.2,
    image: require('../../aseets/khana4.png'),
    details: 'McFeast features two 100% fresh beef burger patties that are hot',
    preferenceTitle: [
      'Choose your 2 dips',
      'Choose your 1st drink flavour',
      'Choose your 2nd drink flavour',
      'Would you like to add a side?',
      'Would you Like any extra sauce?',
    ],
    preferenceData: [
      [
        {name: 'Jalapeno Dip', price: 8.91, checked: false, id: 10},
        {name: 'Sweet & Sour Dip', price: 8.75, checked: false, id: 11},
        {name: 'BBQ Dip', price: 11.99, checked: false, id: 12},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 13},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 14},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 15},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 16},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 17},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 18},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 19},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 20},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 21},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 22},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 23},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 24},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 25},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 26},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 27},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 28},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 29},
      ],

      [
        {name: 'debonairs sauce', price: 8.9, checked: false, id: 30},
        {name: 'BBQ Sauce', price: 8.9, checked: false, id: 31},
        {name: 'Tikka Sauce', price: 11.9, checked: false, id: 32},
      ],

      [
        {name: 'Small Coke', price: 8.9, checked: false, id: 33},
        {name: 'Small Fanta Orange', price: 8.9, checked: false, id: 34},
        {name: 'Small Sprite', price: 11.9, checked: false, id: 35},
        {name: 'Small Coke Zero', price: 3.95, checked: false, id: 36},
        {name: 'Small Syoney Zero', price: 3.95, checked: false, id: 37},
        {name: 'Small Apple Juice', price: 10.95, checked: false, id: 38},
        {name: 'Small Strawberry Shake', price: 16.95, checked: false, id: 39},
        {name: 'Small Chocolate Shake', price: 16.95, checked: false, id: 40},
        {name: 'Small Vanilla Shake', price: 17.95, checked: false, id: 41},
      ],
    ],
    minimum_quatity: [2, 1, 1, null, null],
    counter: [0, 0, 0, 0, 0],
    required: [true, true, true, false, false],
    id: 5,
    type: 'todo',
  },
];

export const review_data = [
  {
    _id: '5d7a514b5d2c12c7449be020',
    title: 'Learned a ton!',
    text: 'Lorem ipsum scelerisque',
    rating: 2,
    bootcamp: '5d713995b721c3bb38c1f5d0',
    user: '5c8a1d5b0190b214360dc033',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be021',
    title: 'Great bootcamp',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 2,
    bootcamp: '5d713995b721c3bb38c1f5d0',
    user: '5c8a1d5b0190b214360dc034',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be022',
    title: 'Got me a developer job',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 3,
    bootcamp: '5d713a66ec8f2b88b8f830b8',
    user: '5c8a1d5b0190b214360dc035',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be023',
    title: 'Not that great',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 3,
    bootcamp: '5d713a66ec8f2b88b8f830b8',
    user: '5c8a1d5b0190b214360dc036',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be024',
    title: 'Great overall experience',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 1,
    bootcamp: '5d725a037b292f5f8ceff787',
    user: '5c8a1d5b0190b214360dc037',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be025',
    title: 'Not worth the money',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur ',
    rating: 1,
    bootcamp: '5d725a037b292f5f8ceff787',
    user: '5c8a1d5b0190b214360dc038',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be026',
    title: 'Best instructors',
    text: 'Lorem ipsum dolor e',
    rating: 1,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc039',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be027',
    title: 'Was worth the investment',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 1,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc040',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be027',
    title: 'Was worth the investment',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 4,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc040',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be027',
    title: 'Was worth the investment',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 4,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc040',
    reaction: {info: 0, heart: 0, bad: 0},
  },
  {
    _id: '5d7a514b5d2c12c7449be027',
    title: 'Was worth the investment',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 5,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc040',
  },
  {
    _id: '5d7a514b5d2c12c7449be026',
    title: 'Best instructors',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 1,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc039',
  },
  {
    _id: '5d7a514b5d2c12c7449be026',
    title: 'Best instructors',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 1,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc039',
  },
  {
    _id: '5d7a514b5d2c12c7449be026',
    title: 'Best instructors',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec viverra feugiat mauris id viverra. Duis luctus ex sed facilisis ultrices. Curabitur scelerisque bibendum ligula, quis condimentum libero fermentum in. Aenean erat erat, aliquam in purus a, rhoncus hendrerit tellus. Donec accumsan justo in felis consequat sollicitudin. Fusce luctus mattis nunc vitae maximus. Curabitur semper felis eu magna laoreet scelerisque',
    rating: 1,
    bootcamp: '5d725a1b7b292f5f8ceff788',
    user: '5c8a1d5b0190b214360dc039',
  },
];

export const Users = [
  {
    _id: '5d7a514b5d2c12c7449be042',
    name: 'Admin Account',
    email: 'admin@gmail.com',
    role: 'user',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5d7a514b5d2c12c7449be043',
    name: 'Publisher Account',
    email: 'publisher@gmail.com',
    role: 'publisher',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5d7a514b5d2c12c7449be044',
    name: 'User Account',
    email: 'user@gmail.com',
    role: 'user',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5d7a514b5d2c12c7449be045',
    name: 'John Doe',
    email: 'john@gmail.com',
    role: 'publisher',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5d7a514b5d2c12c7449be046',
    name: 'Kevin Smith',
    email: 'kevin@gmail.com',
    role: 'publisher',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc031',
    name: 'Mary Williams',
    email: 'mary@gmail.com',
    role: 'publisher',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc032',
    name: 'Sasha Ryan',
    email: 'sasha@gmail.com',
    role: 'publisher',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc033',
    name: 'Greg Harris',
    email: 'greg@gmail.com',
    role: 'user',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc034',
    name: 'Derek Glover',
    email: 'derek@gmail.com',
    role: 'user',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc035',
    name: 'Stephanie Hanson',
    email: 'steph@gmail.com',
    role: 'user',
    password: '123456',
    image: require('../../aseets/profile.jpg'),
  },
  {
    _id: '5c8a1d5b0190b214360dc036',
    name: 'Jerry Wiliams',
    email: 'jerry@gmail.com',
    role: 'user',
    password: '123456',
  },
  {
    _id: '5c8a1d5b0190b214360dc037',
    name: 'Maggie Johnson',
    email: 'maggie@gmail.com',
    role: 'user',
    password: '123456',
  },
  {
    _id: '5c8a1d5b0190b214360dc038',
    name: 'Barry Dickens',
    email: 'barry@gmail.com',
    role: 'user',
    password: '123456',
  },
  {
    _id: '5c8a1d5b0190b214360dc039',
    name: 'Ryan Bolin',
    email: 'ryan@gmail.com',
    role: 'user',
    password: '123456',
  },
  {
    _id: '5c8a1d5b0190b214360dc040',
    name: 'Sara Kensing',
    email: 'sara@gmail.com',
    role: 'user',
    password: '123456',
  },
];
